run:
  timeout: 3m
  tests: true

linters:
  enable:
    - gosimple
    - gocritic
    - gofmt
    - govet
    - staticcheck
    - errcheck
    - bodyclose
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: false
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
  goimports:
    local-prefixes: 'github.com/spanwalla/song-library'

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck